### ISSUE TITLE
Add header 'Bijlage' in rendered pdf

### ISSUE THREAD

**Issue by ToonHub** [inbo/protocolhelper#108]
Header 'Bijlage' is currently missing, which might be confusing

**Comment by hansvancalster** [comment]
The header `# (APPENDIX) Bijlagen {.unnumbered}` is treated in a [special way by bookdown](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#special-headers). The word "Bijlagen" is only visible in the html version on the left hand side in the table of contents navigation bar.

I think it is already clear visually how appendices are rendered in html and pdf. They all start with A., B., ... instead of chapter numbers and they appear after the references. If you want to make it more clear, you could be more explicit by adding the word "Bijlage" before each title:

```
# (APPENDIX) Bijlagen {.unnumbered}

# Bijlage: titel van de eerste bijlage

bla bla

# Bijlage: titel van de tweede bijlage

...
```

But personally I don't find this necessary.

**Comment by hansvancalster** [comment]
I think this issue can also be closed.
