### ISSUE TITLE
error `yml$subtitle is not a string` in `check_frontmatter()`

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/protocolhelper#59]
Running function `check_frontmatter()` on a protocol with no subtitle gives an error, I don't know is this is intended behaviour?

E.g. running
`protocolhelper::check_frontmatter(protocol_code = "sfp-401-nl")`

gives the error:
`Error: yml$subtitle is not a string (a length one character vector).`

**Comment by hansvancalster** [comment]
This is not intended. Can you fix this?

**Comment by ElsLommelen** [comment]
Eh, how would you like me to fix it?  I see 2 possibilities:
- I just allow subtitle to be empty so the test will pass with subtitle which is declared and empty
- I give an error if subtitle is empty, asking the user to remove it in the heading if it is not used (does not have a value)

I don't know the details of the system, so I don't know which is best?  For instance: if dealing with subtitles in the code, do you always verify if subtitle is empty?  Could an empty subtitle cause problems?  Or on the other hand: could the absence of the variable subtitle cause problems?...

So I don't mind fixing, but can you please decide on the best way to fix it from your experience with the package?

**Comment by hansvancalster** [comment]
Currently, `create_protocol(..., subtitle, ....)` checks if subtitle is a string. I think this should be relaxed because a subtitle is optional. So that function should only make this check if the argument is not missing. (writing `create_protocol(..., subtitle = "", ....)` is not ideal because it will render unnecessary white lines?)

Next thing to do is to make sure that if `create_protocol(..., subtitle, ....)` has missing subtitle, no subtitle key is written to the yaml header.

I guess this means that I prefer the second option that you give for `check_frontmatter`. However, I suspect this may break ´render_release´ when a subtitle is missing. So that will be another thing to look into.

**Comment by ElsLommelen** [comment]
Are there other optional arguments in the yaml header that can serve as an example on how to deal with 'subtitle' in `create_protocol()`?

In `render_release()`, 'subtitle' only occurs twice in the code, so it looks rather easy to solve the problem there.

**Comment by hansvancalster** [comment]
I don't have an example, `subtitle` is the only optional one. I think the easiest way may be to use `subtitle = NULL` as default. In that way you can check in `create_protocol` if it is a string when not NULL and use `ymlthis::yml_discard("subtitle")` if it is NULL (this will need to come after the `ymlthis::yml_replace(...., subtitle = subtitle, ...)` code inside `create_protocol`.

**Comment by hansvancalster** [comment]
closed as completed
